# /////////////////////////////////////////////////////////////
# @file: pd-imagine/Dockerfile.python-dev
# @brief: This Dockerfile sets up a Python development environment on Ubuntu 24.04.
# /////////////////////////////////////////////////////////////

# === Use an official Ubuntu 24.04 (noble numbat) as a base image 
# @see: https://hub.docker.com/_/ubuntu
# @note: Ubuntu image has a default non-root user named `ubuntu`, with user id 1000, group id 1000 and this dockerfile is designed to use that one.
FROM ubuntu:24.04

SHELL ["/bin/bash", "-euc"]

# === Basic Scaffolding
ENV TZ='Asia/Tokyo'
ENV LANG='C.UTF-8'
ENV LC_ALL='C.UTF-8'

# Install packages for Python development
# @note: The here doc (<<-EOT) strips leading tabs from the content, allowing for cleaner indentation in the Dockerfile.
RUN <<-EOT
	export DEBIAN_FRONTEND=noninteractive
	apt-get update
	apt-get install -y --no-install-recommends \
		tzdata \
		wget gnupg ca-certificates \
		openssh-client git nano tmux \
		sudo \
		python3 python3-pip python3-venv python3-dev
	apt-get clean
	rm -rf /var/lib/apt/lists/*
EOT

# === Setup Python development environment

# Create Python virtual environment and install packages
COPY --chmod=0644 copy/install/requirements.txt /tmp/requirements.txt
RUN <<-EOT
	python3 -m venv /opt/venv
	/opt/venv/bin/pip install --no-cache-dir --upgrade pip
	/opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements.txt
	rm /tmp/requirements.txt
EOT

# === Work env. setup

# --- Create a non-root user
# Create a non-root user with the specified UID and GID and grant sudo privileges
# @note: Ubuntu image has a default non-root user named `ubuntu`, with user id 1000, group id 1000 and this dockerfile is designed to use that one.
ARG PD_USER_NAME='ubuntu'
ARG PD_USER_UID='1000'
ARG PD_USER_GID=$PD_USER_UID
ARG PD_USER_HOME="/home/${PD_USER_NAME}"
ARG PD_WORKSPACE="${PD_USER_HOME}/wksp"
RUN <<-EOT
	echo "${PD_USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$PD_USER_NAME
	chmod 0440 /etc/sudoers.d/$PD_USER_NAME
EOT

# --- Setup tmux ---
COPY --chmod=0644 copy/config/tmux-conf /tmp/tmux-conf
RUN <<-EOT
	cp /tmp/tmux-conf $PD_USER_HOME/.tmux.conf
	chown $PD_USER_NAME:$PD_USER_NAME $PD_USER_HOME/.tmux.conf
EOT

# --- Setup SSH ---
COPY --chmod=0600 copy/config/ssh-conf /tmp/ssh-conf
RUN <<-EOT
	[ -d "$PD_USER_HOME/.ssh" ] || mkdir $PD_USER_HOME/.ssh
	chown $PD_USER_NAME:$PD_USER_NAME $PD_USER_HOME/.ssh
	cp /tmp/ssh-conf $PD_USER_HOME/.ssh/config
	chown $PD_USER_NAME:$PD_USER_NAME $PD_USER_HOME/.ssh/config
EOT

# --- Setup GPG ---
# Create the necessary directory structure for gpg forwarding
# @note: This directory is automatically created on Ubuntu Desktop, but it does not exist by default for a Ubuntu docker image.
RUN <<-EOT
	mkdir -p -m 0700 /run/user/$PD_USER_UID
	chown $PD_USER_NAME:$PD_USER_NAME /run/user/$PD_USER_UID
EOT

# --- Clean up ---
RUN rm -rf /tmp/*

# --- Launchpad
USER $PD_USER_NAME

ENV USER=$PD_USER_NAME
ENV HOME=$PD_USER_HOME
ENV SHELL='/bin/bash'
# Make sure the virtual python environment is activated
ENV PATH="/opt/venv/bin:$PATH"
ENV VIRTUAL_ENV="/opt/venv"

# Set the working directory in the *container*
WORKDIR $PD_WORKSPACE

# Set the default command
CMD echo "PLEASE LOGIN TO THE CONTAINER AND RUN THE SERVICE MANUALLY" && \
	echo "@host: docker run -it <image-name> bash" && \
	echo "@docker: <your-command-here>"
