name: build-and-push-pd-imagine
run-name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches: [ feature/** ]
  workflow_dispatch: # Allows manual triggering

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        image_type: [ros-noetic-dev]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract Metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_type }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title=PD-Imagine ${{ matrix.image_type }}
          org.opencontainers.image.description=Docker image for PD-Imagine project - ${{ matrix.image_type }}
          org.opencontainers.image.vendor=madpang
          org.opencontainers.image.version=${{ github.sha }}

    - name: Build, Tag and Push Image
      run: |
        LOCAL_IMAGE=""
        case "${{ matrix.image_type }}" in
          "ros-noetic-dev")
            ./build.sh create_ros_noetic_dev_image
            LOCAL_IMAGE="pd-imagine/ros-noetic-dev:latest"
            ;;
          "qt6-dev-vnc")
            ./build.sh create_qt6_dev_vnc_image
            LOCAL_IMAGE="pd-imagine/qt6-dev-vnc:latest"
            ;;
          "ros1-qt6-vnc")
            ./build.sh create_ros1_qt6_vnc_image
            LOCAL_IMAGE="pd-imagine/ros1-qt6-vnc:latest"
            ;;            
        esac

        if [ -n "$LOCAL_IMAGE" ]; then
          echo "${{ steps.meta.outputs.tags }}" | while read -r tag; do
            if [ -n "$tag" ]; then
              echo "Tagging $LOCAL_IMAGE as $tag"
              docker image tag $LOCAL_IMAGE $tag
              echo "Pushing $tag"
              docker image push $tag
            fi
          done
        else
          echo "LOCAL_IMAGE is undefined, skipping tagging and pushing."
        fi
